---
title: Prerequisites for FlowEHR
---

## The skills you need

- Familiarity with **Python** programming for data science tasks. Much of the design of the platform is orientated to support those with strong SQL skills, or those with strong R skills, but for now you will find that the examples and the work are biased toward Python.

## The permissions you need

- We assume that you are working in a _direct care_ role and therefore have rights to access identifiable data.

## The resources you need

- Some time and some patience!

## Recommendations

We're not _telling_ you to do the following, but these are the sort of things you might want to consider if you hit problems.

- We recommend using the [Microsoft Authenticator](https://www.microsoft.com/security/mobile-authenticator-app) for your two-factor authentication. You will likely end up with multiple accounts (at a minimum, one for the trusted research environment and one for NHS.net), and for most authenticators this will mean you need you need to work out which code is for which account. With the Microsoft Authenticator you will get push notifications when trying to log in, and you can then Approve the login directly. 
- Try using [Microsoft Edge](https://www.microsoft.com/edge) as your browser for working with the TRE. It just seems to work better with this tooling.

It's going to get confusing at times. There's a lot of new terminology. Please check-out the [FAQ](../faq/faq.qmd).