project:
  type: website
  preview:
    port: 8235

execute:
  freeze: auto

website:
  title: "FlowEHR Garden Path"
  description: "End user documentation for FlowEHR"
  navbar:
    logo: images/logo-dark.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: https://www.flowehr.io
        text: FlowEHR.io
      # choose your own adventure
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/UCLH-Foundry/Garden-Path
        aria-label: GitHub
  page-navigation: true
  page-footer: |
    Built for the NHS | 2022-2023
  sidebar:
    style: docked
    contents:
      - section: Quick start
        contents:
          - href: quickstart/10_prerequisites.qmd
            text: Prerequisites
          - href: quickstart/20_setup_overview.qmd
            text: Set-up
            contents:
              - href: quickstart/20_setup_conda.qmd
                text: Conda environments
              - href: quickstart/20_setup_ads.qmd
                text: Azure Data Studio
              - href: quickstart/20_setup_gitea.qmd
                text: Gitea
              - href: quickstart/20_setup_vm.qmd
                text: Virtual Machines
              - href: quickstart/20_setup_vscode.qmd
                text: Visual Studio Code
              - href: quickstart/20_setup_flowehr_locally.qmd
                text: FlowEHR locally
          - href: quickstart/30_connecting.qmd
            text: Connecting to data
          - href: quickstart/40_features.qmd
            text: Feature building
          - href: quickstart/50_modelling.qmd
            text: Modelling
          - href: quickstart/60_deployment.qmd
            text: Application deployment
          - href: quickstart/70_stewardship.qmd
            text: Stewardship
      - section: "Who am I?"
        contents:
          - href: personas/personas.qmd
            text: Personas
      - section: The Data Scientist
        contents:
          - href: personas/datascientist/datascientist.qmd
            text: Overview
          - href: personas/datascientist/onboarding.qmd
            text: Onboarding
      - section: The Developer
        contents:
          - href: personas/developer/developer.qmd
            text: Overview
          - href: personas/developer/building-an-app.qmd
            text: Building an App
      - section: The Administrator
        contents:
          - href: personas/administrator/administrator.qmd
            text: Overview
          - href: personas/administrator/configuration.qmd
            text: Configuration
      - section: The Steward
        contents:
          - href: personas/steward/steward.qmd
            text: Overview
      - section: Anatomy of FlowEHR
        contents:
          - href: anatomy/tre.qmd
            text: Trusted Research Environment
          - href: anatomy/vm.qmd
            text: Virtual Machines
          - href: anatomy/apps.qmd
            text: FlowEHR Apps
      - section: "User Contributions"
        contents:
          - href: vignettes/vignettes.qmd
            text: Vignettes
          - href: faq/faq.qmd
            text: FAQ
  repo-url: https://github.com/UCLH-Foundry/Garden-Path
  repo-actions: [edit, issue]
  repo-subdir: docs

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
      dark: [darkly, scss/dark.scss]
    css: scss/styles.css
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    number-sections: true

